//[example_output
> example --log_level=message
Running 1 test case...
test.cpp(8): error in "free_test_function": check 2 == 1 has failed
Test case has less failures then expected

*** No errors detected
//]